"""
routes/chat.py — POST /chat

Accepts a user message + session history, runs the RAG pipeline:
  1. Embed the user query
  2. Retrieve top-K semantically similar chunks from ChromaDB
  3. Build a grounded, hallucination-resistant prompt
  4. Send to Gemini 1.5 Flash
  5. Return the answer with source metadata

Session history is sent by the client on every request (stateless server
design — simplifies horizontal scaling on Render's free tier).
"""

from __future__ import annotations

from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import JSONResponse
from loguru import logger
from pydantic import BaseModel, Field

from config import get_settings
from rag.retriever import RAGRetriever
from rag.generator import ResponseGenerator

router = APIRouter()
settings = get_settings()


# ------------------------------------------------------------------ #
#  Request / response schemas                                          #
# ------------------------------------------------------------------ #

class ChatMessage(BaseModel):
    role: str = Field(..., description="'user' or 'assistant'")
    content: str = Field(..., description="Message text")


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="The user's current message",
    )
    session_id: str = Field(
        ...,
        description="Unique session identifier (UUID generated by the client)",
    )
    history: list[ChatMessage] = Field(
        default_factory=list,
        description="Conversation history (last N turns)",
    )


class SourceChunk(BaseModel):
    document_id: str
    filename: str
    chunk_index: int
    content_preview: str


class ChatResponse(BaseModel):
    answer: str
    session_id: str
    sources: list[SourceChunk]
    retrieval_count: int


# ------------------------------------------------------------------ #
#  Route                                                               #
# ------------------------------------------------------------------ #

@router.post(
    "",
    summary="Chat with the banking assistant",
    description=(
        "Send a message and receive a grounded answer generated from the "
        "uploaded knowledge base. Includes source citations."
    ),
    response_model=ChatResponse,
)
async def chat(request: Request, body: ChatRequest) -> JSONResponse:
    """
    RAG chat endpoint.

    Flow:
      embed query → retrieve chunks → build prompt → generate → return
    """
    logger.info(
        f"[session={body.session_id}] User: {body.message[:80]!r}"
    )

    # ---- Retrieve relevant chunks ------------------------------------ #
    try:
        retriever = RAGRetriever(
            vector_store=request.app.state.vector_store,
            embedder=request.app.state.embedder,
            top_k=settings.top_k_results,
        )
        chunks = retriever.retrieve(query=body.message)
    except Exception as exc:
        logger.exception(f"Retrieval error: {exc}")
        raise HTTPException(
            status_code=500,
            detail=f"Retrieval failed: {exc}",
        )

    # ---- Generate grounded response ---------------------------------- #
    try:
        generator = ResponseGenerator(
            api_key=settings.gemini_api_key,
            model=settings.gemini_model,
            groq_api_key=settings.groq_api_key,
            groq_model=settings.groq_model,
        )
        answer = generator.generate(
            query=body.message,
            chunks=chunks,
            history=[(m.role, m.content) for m in body.history],
        )
    except Exception as exc:
        logger.exception(f"Generation error: {exc}")
        raise HTTPException(
            status_code=500,
            detail=f"Response generation failed: {exc}",
        )

    # ---- Build source list ------------------------------------------- #
    sources = [
        SourceChunk(
            document_id=c["document_id"],
            filename=c["filename"],
            chunk_index=c["chunk_index"],
            content_preview=c["content"][:200] + ("…" if len(c["content"]) > 200 else ""),
        )
        for c in chunks
    ]

    logger.info(
        f"[session={body.session_id}] "
        f"Retrieved {len(chunks)} chunks → answer generated"
    )

    return JSONResponse(
        content={
            "answer": answer,
            "session_id": body.session_id,
            "sources": [s.model_dump() for s in sources],
            "retrieval_count": len(chunks),
        }
    )
